#!/usr/bin/env python
"""
pyt by Preston Hunt <me@prestonhunt.com>

Helper for yt-dlp that applies useful defaults.
"""

import argparse
import subprocess
import sys


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument('urls', nargs='*', help='urls to download')
    parser.add_argument('--extract-audio', '-x', action='store_true', help='audio only')

    return parser.parse_args()


def main():
    for url in ARGS.urls:
        get_url(url)


def get_url(url):
    args = [
        "yt-dlp", url,
        "--restrict-filenames",  # Only ASCII characters, avoid "&" and spaces in filenames
        "--trim-filenames=200",  # Limit filename length
        "--embed-metadata",      # Embed all available metadata in the output file
    ]

    filename = url.partition("//")[-1].replace("/", "-")

    if ARGS.extract_audio:
        args += [
            "--extract-audio",
            "--embed-thumbnail",
            "--convert-thumbnail", "jpg",
            "--output", "%(artist)s - %(title)s.%(ext)s"
        ]
    else:
        args += [
            "--merge-output-format=mkv",  # Use mkv which allows unlimited metadata
            "--write-subs",               # Save subtitles
            "--output", filename
        ]

    print(args)
    subprocess.run(args)


def run(*args):
    return subprocess.run(args, capture_output=True, text=True)


class Fail(Exception):
    pass


if __name__ == '__main__':
    try:
        # Command-line arguments are considered as immutable constants of the
        # universe, and thus are globally available in this script.
        ARGS = parse_args()
        main()
    except Fail as f:
        print(*f.args, file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("Ctrl+C")
