#!/usr/bin/env python
"""
psnap by Preston Hunt <me@prestonhunt.com>

Helper to view and manage ZFS snapshots.
"""

import argparse
import json
import subprocess
import sys


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('datasets', nargs='+', help='names of datasets to process')
    parser.add_argument('--rm', default=False, action='store_true', help='remove first dataset')
    parser.add_argument('--first', '-1', default=False, action='store_true', help='first dataset only')
    parser.add_argument('--verbose', "-v", default=False, action='store_true', help='show details')
    return parser.parse_args()


def main():
    datasets = []
    for dataset in ARGS.datasets:
        datasets += get_datasets(dataset)

    if ARGS.first:
        datasets = datasets[:1]

    if len(datasets) == 1:
        # automatic verbose mode
        ARGS.verbose = True

    for dataset in datasets:
        process_dataset(dataset)


def process_dataset(dataset):
    space_before = get_usedbysnapshots(dataset)
    space_after = space_before
    print(f"{_gb(space_before)}  {dataset}")

    for snapshot in get_snapshots(dataset):
        name = snapshot['name']
        used_bytes = int(snapshot['properties']['used']['value'])
        if ARGS.verbose:
            print(f"{_gb(used_bytes)}  {name}")
        if ARGS.rm:
            remove_snapshot(name)
            space_after = get_usedbysnapshots(dataset)
            if space_after != space_before:
                bytes_freed = space_before - space_after
                print(f"{_gb(bytes_freed)}  freed")
            print(f"{_gb(space_after)}  total used by snapshots")
            break


def get_datasets(top_dataset):
    j = run_json(["zfs", "list", "-t", "filesystem", top_dataset, "-r", "--json", "-p"])
    if not j:
        raise Fail(f"{top_dataset}: dataset does not exist")
    for name in j['datasets']:
        yield name


def get_snapshots(dataset):
    j = run_json(["zfs", "list", "-t", "snapshot", dataset, "--json", "-p"])
    for name, snapshot in j['datasets'].items():
        yield snapshot


def remove_snapshot(name):
    subprocess.run(["sudo", "zfs", "destroy", name])


def get_usedbysnapshots(name):
    j = run_json(["zfs", "list", "-o", "space", "--json", "-p", name])
    used = int(j['datasets'][name]['properties']['usedbysnapshots']['value'])
    return used


def run_json(cmd) -> dict | None:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        return None
    return json.loads(result.stdout)


def _gb(bytes):
    return f"{bytes / 1024**3:>6.1f} GiB"


class Fail(Exception):
    pass


if __name__ == '__main__':
    try:
        ARGS = parse_args()
        main()
    except Fail as f:
        print(*f.args, file=sys.stderr)
        raise SystemExit(1)
    except KeyboardInterrupt:
        print("Ctrl+C")
