#!/usr/bin/env python

"""
pinfo by Preston Hunt <me@prestonhunt.com>
https://github.com/presto8/pythonskeletonsimple

Provide information about files, similar to the `file` program but more detailed.
"""

import argparse
import json
import subprocess
import sys

from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter, add_help=False)

    parser.add_argument('paths', nargs='+', help='paths to process')

    return parser.parse_args()


def get_longest_string_length(strings: list[str]) -> int:
    return max(len(s) for s in strings)


def main():
    global MAX_PATH_LENGTH
    MAX_PATH_LENGTH = get_longest_string_length(str(path) for path in ARGS.paths)

    for path in ARGS.paths:
        showinfo(Path(path))


class InfoHandlerError(Exception):
    pass


class InfoHandler:
    """Abstract base class for handling different file types. Subclasses should
    implement the `showinfo` method. If the file type is not supported, the
    `showinfo` method should raise an `InfoHandlerError` exception."""

    def showinfo(self, path: Path):
        "Override this method to show information about the file at `path`."
        raise InfoHandlerError()

    def print(self, *args, **kwargs):
        path_fmt = f"{self.path.name:<{MAX_PATH_LENGTH}} "
        print(path_fmt, *args, **kwargs)


class StreamInfo(dict):
    pass


class VideoInfoHandler(InfoHandler):
    def showinfo(self, path: Path):
        self.path = path

        extensions = ".mp4 .mkv .avi .wmv .mov .vob".split()
        if path.suffix.lower() not in extensions:
            raise InfoHandlerError()

        streaminfo = self.get_stream_info(path)
        parts = []

        for video_info in self.get_video_info(streaminfo):
            parts += [f"{video_info},"]

        for audio_info in self.get_audio_info(streaminfo):
            parts += [audio_info]

        if parts:
            self.print(*parts)
            return

        raise InfoHandlerError()

    @staticmethod
    def get_stream_info(path) -> StreamInfo:
        cmd = "ffprobe -print_format json -show_format -show_streams".split() + [path]
        result = subprocess.run(cmd, capture_output=True, text=True)
        return json.loads(result.stdout)

    @staticmethod
    def get_audio_info(streaminfo: StreamInfo):
        for stream in streaminfo['streams']:
            if stream['codec_type'] == 'audio':
                parts = [stream['codec_name']]
                try:
                    result = int(stream['bit_rate'])
                except KeyError:
                    continue
                parts += [f"{result // 1000}k"]
                yield " ".join(parts)

    @staticmethod
    def get_video_info(streaminfo: StreamInfo):
        for stream in streaminfo['streams']:
            if stream['codec_type'] == 'video':
                # print(stream)
                parts = [stream['codec_name']]
                if profile := stream.get('profile', None):
                    parts += [f"({profile})"]
                parts += [f"{stream['width']}x{stream['height']}"]
                if bit_rate := stream.get('bit_rate', None):
                    parts += [f"{int(bit_rate) // 1000}k"]
                yield " ".join(parts)


class DirectoryInfoHandler(InfoHandler):
    def showinfo(self, path: Path):
        self.path = path

        if not path.is_dir():
            raise InfoHandlerError()

        if path.is_symlink():
            raise InfoHandlerError()

        size = 0
        items = 0
        files = 0
        subdirs = 0
        for item in path.rglob("*"):
            items += 1
            if item.is_dir() and not item.is_symlink():
                subdirs += 1
            else:
                files += 1
            size += item.stat().st_size
        self.print(f"directory: {files:>5} files {subdirs:>5} subdirs {size:>15,} bytes")


class FallbackInfoHandler(InfoHandler):
    """If nothing else matches, use the `file` program to show basic information about the file."""
    def showinfo(self, path: Path):
        self.path = path

        result = subprocess.run(["file", "--brief", path.name], capture_output=True, text=True)
        self.print(result.stdout.strip())


HANDLERS = [
    VideoInfoHandler,
    DirectoryInfoHandler,
    FallbackInfoHandler
]


def showinfo(path: Path):
    for handler in HANDLERS:
        try:
            handler().showinfo(path)
            return
        except InfoHandlerError:
            continue
    print("unhandled:", path)


def run(*args):
    return subprocess.run(args, capture_output=True, text=True)


class Fail(Exception):
    pass


if __name__ == '__main__':
    try:
        # Command-line arguments are considered as immutable constants of the
        # universe, and thus are globally available in this script.
        ARGS = parse_args()
        main()
    except Fail as f:
        print(*f.args, file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("Ctrl+C")
